# Generated by Django 3.2.9 on 2022-01-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
