# Generated by Django 3.2.9 on 2022-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weekly_discount_notif_required',
            field=models.BooleanField(default=True),
        ),
    ]
