# Generated by Django 3.2.9 on 2022-01-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_user_weekly_discount_notif_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='date_expire',
            field=models.DateTimeField(),
        ),
    ]
