# Generated by Django 3.2.9 on 2022-01-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_alter_discount_date_expire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_value', models.IntegerField()),
                ('sufficient_amount_to_subtract', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='amount_price',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
