# Generated by Django 3.2.9 on 2022-01-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_auto_20220129_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cashback_points',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
