# Generated by Django 3.2.9 on 2022-01-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_user_cashback_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cashback_points',
            field=models.FloatField(default=0.0),
        ),
    ]
