# Generated by Django 3.2.9 on 2022-01-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_alter_user_cashback_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
